model_path : 'my_models\character.pt'
imgsz : 128
conf_thres : 0.5
iou_thres : 0.45
max_det : 1000
class_name : ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B',
              'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
              'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'] 

color_map : [[255, 0 ,0], [255, 255, 0], [0, 255, 0], [0, 255, 255], [0, 0, 255],  
            [125, 0, 100], [200, 100, 50], [100, 200, 50], [50, 150, 200], [150, 0, 200],
            [50, 150, 50], [150, 50, 150], [100, 100, 250], [255, 0 , 50], [50, 50 ,0],
            [50, 80, 90], [200, 0 , 200], [255, 155, 70], [0, 0, 70], [0, 70, 0], [255, 0 , 111],
            [88, 88, 88], [155, 155, 155], [200, 200, 200], [99, 199, 9], [44, 244, 144], [9, 9, 9],
            [99, 9, 9], [156, 255, 2], [155, 0, 10], [50, 200, 80], [57, 90, 80], [57, 90, 20], [50, 60, 70], [70, 60, 50], [70, 77, 59]]

agnostic_nms : False
device : 'cuda'
auto : False 
stride : 16
line_thickness : 1
line_size : 0.6
hide_confidence : True
